server:
  port: 21413
  servlet:
    context-path: /
    session:
      timeout: 600s

spring:
  datasource:
    people:
      url: jdbc:postgresql://localhost:5432/users
      username: postgres
      password: nnik1320
      driver-class-name: org.postgresql.Driver
    articles:
      url: jdbc:postgresql://localhost:5432/news
      username: postgres
      password: nnik1320
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

app:
  jwtSecret: 77BB8D1285FF9F029850511B3ECC8B0EA3DFFB0987762701471144681C07F4E4B8D1285FF9F029850511B3DFFB0987762701471144
  jwtExpirationPeriod: 30
  refreshTokenExpirationPeriod: 1440

logging:
  level:
    org:
      springframework:
        security: DEBUG